[required]
target_mac = [
  "12:34:56:AA:CC:EE",
  "22:34:56:bb:cc:ee",
  "554456BBCCEE",
  "ab3423febc3d",
]
interface = ["wlp0s20f0u3u1"]

[optional]
target_ssid = ["ExampleSSID1", "ExampleSSID2", "TestNetwork"]
kismet_endpoint = "127.0.0.1:2501"

# Kismet Credentials
[credentials]
user = "test"
password = "test"
